version: '3.0'
services:
  app:
    image: daipham99/linux-nginx:latest
    container_name: app
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/app
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=&sK@rI018r37
      - MYSQL_DATABASE=backend
      - MYSQL_DATABASE=backend_testing
    volumes:
      - ./docker/database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql      