version: '3.0'
services:
  app:
    build: .
    container_name: app
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/app
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=&sK@rI018r37
      - MYSQL_DATABASE=backend
    volumes:
      - ./docker/database:/var/lib/mysql